### ISSUE TITLE
Featured image height should be known on render

### ISSUE THREAD

**Issue by luisherranz** [imranhsayed/frontity-twentynineteen#7]
To prevent the text from "jumping", the image height should be known prior to the image render.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/3305402/61701631-ca974680-ad3e-11e9-85f2-0ceefb08aeb0.gif)

Like here:
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/3305402/61702414-0c74bc80-ad40-11e9-9c97-0174f098e443.gif)

**Comment by imranhsayed** [comment]
Please review the following PR:
https://github.com/imranhsayed/frontity-twentynineteen/pull/13
Fixes image height issue with following steps:

1. Calculate the image container width in relation to window prior to image render.
2. Get the required image height in proportion to the actual image size and the size of the container.
3. Set the container height to the required image height.

**Bug:**
window element is not found intermittently in the component.

**Comment by luisherranz** [comment]
Fixed by https://github.com/imranhsayed/frontity-twentynineteen/pull/18 👍
